import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Search, Trash2, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { useNavigate } from "react-router-dom";
import { adminApi } from "@/api/crmApi";
import PageHeader from "@/components/common/PageHeader";
import DataTable from "@/components/common/DataTable";
import LoadingState from "@/components/common/LoadingState";
import ErrorState from "@/components/common/ErrorState";
import StatusBadge from "@/components/common/StatusBadge";
import ConfirmDialog from "@/components/common/ConfirmDialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { formatDateTime, titleCase } from "@/utils/format";
import { getErrorMessage } from "@/utils/errors";

const modules=["CUSTOMER_CREATE","CUSTOMER_UPDATE","CUSTOMER_DELETE","CONTACT_CREATE","VISIT_BACKDATE","CUSTOMER_SAMPLING","SELF_STOCK"];
function HistoryDetails({ id, open, onOpenChange }){const nav=useNavigate();const q=useQuery({queryKey:["admin-history-detail",id],queryFn:()=>adminApi.requestHistoryDetails(id),enabled:Boolean(open&&id)});return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-4xl"><DialogTitle>Approval Audit Trail</DialogTitle><DialogDescription>Immutable approval/action detail remains in operational approval tables even when an Admin audit list entry is removed.</DialogDescription>{q.isLoading?<LoadingState/>:q.isError?<ErrorState error={q.error}/>:q.data&&<div className="mt-5 space-y-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["Request",q.data.history.request_number],["Module",titleCase(q.data.history.module_name)],["Status",q.data.history.status],["Requester",`${q.data.history.requested_by} (${q.data.history.requester_profile_code})`]].map(([k,v])=><div key={k} className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><p className="text-[11px] uppercase text-slate-400">{k}</p><p className="mt-1 text-sm font-semibold">{v||"—"}</p></div>)}</div><div><p className="mb-3 font-bold">Who approved / rejected</p><div className="space-y-3">{(q.data.actions||[]).length?(q.data.actions||[]).map(a=><div key={a.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 p-3 dark:border-slate-700"><div><p className="font-semibold">{a.executive_name} <span className="text-xs text-slate-500">({a.executive_code})</span></p><p className="text-xs text-slate-500">{a.profile_code} · Level {a.approval_level} · {formatDateTime(a.created_at)}</p>{a.remarks&&<p className="mt-1 text-sm">{a.remarks}</p>}</div><StatusBadge status={a.action}/></div>):<p className="text-sm text-slate-500">No action yet.</p>}</div></div>{(q.data.quantityHistory||[]).length>0&&<div><p className="mb-3 font-bold">Quantity decisions</p><div className="grid gap-2 sm:grid-cols-2">{q.data.quantityHistory.map(i=><div key={i.id} className="rounded-xl bg-slate-50 p-3 text-sm dark:bg-slate-800"><p className="font-semibold">{i.title}</p><p className="text-xs text-slate-500">L{i.level_rank}: {i.previous_approved_qty??0} → {i.approved_qty} by {i.approved_by_name}</p></div>)}</div></div>}<div className="flex justify-end"><Button variant="outline" onClick={()=>nav(`/approvals/${q.data.history.approval_request_id}`)}><Eye size={15}/>Open operational approval</Button></div></div>}</DialogContent></Dialog>}

export default function AdminRequestHistoryPage(){const qc=useQueryClient();const [status,setStatus]=useState("");const [module,setModule]=useState("");const [search,setSearch]=useState("");const [selection,setSelection]=useState({});const [detail,setDetail]=useState(null);const [deleting,setDeleting]=useState(null);const q=useQuery({queryKey:["admin-request-history",status,module,search],queryFn:()=>adminApi.requestHistory({status:status||undefined,module:module||undefined,search:search||undefined})});const remove=useMutation({mutationFn:adminApi.deleteHistory,onSuccess:(r)=>{toast.success(r.message);setDeleting(null);qc.invalidateQueries({queryKey:["admin-request-history"]})},onError:(e)=>toast.error(getErrorMessage(e))});const bulk=useMutation({mutationFn:()=>adminApi.bulkDeleteHistory(Object.keys(selection).filter(k=>selection[k]).map(Number)),onSuccess:(r)=>{toast.success(r.message);setSelection({});qc.invalidateQueries({queryKey:["admin-request-history"]})},onError:(e)=>toast.error(getErrorMessage(e))});const columns=useMemo(()=>[
{ id:"select",header:({table})=><Checkbox checked={table.getIsAllRowsSelected()} onChange={table.getToggleAllRowsSelectedHandler()}/>,cell:({row})=><Checkbox disabled={row.original.status==="PENDING"} checked={row.getIsSelected()} onChange={row.getToggleSelectedHandler()} onClick={(e)=>e.stopPropagation()}/>},{accessorKey:"request_number",header:"Request",cell:({row})=><div><p className="font-mono text-xs font-bold text-brand-700">{row.original.request_number}</p><p className="text-xs text-slate-500">{titleCase(row.original.module_name)}</p></div>},{accessorKey:"requested_by",header:"Requested By",cell:({row})=><div><p className="font-semibold">{row.original.requested_by}</p><p className="text-xs text-slate-500">{row.original.requested_by_code} · {row.original.requester_profile_code}</p></div>},{accessorKey:"status",header:"Status",cell:({getValue})=><StatusBadge status={getValue()}/>},{accessorKey:"current_approver",header:"Current / Last",cell:({row})=><div><p className="text-sm font-semibold">{row.original.status==="PENDING"?(row.original.current_approver||"—"):(row.original.last_action_by||"—")}</p><p className="text-xs text-slate-500">{row.original.status==="PENDING"?(row.original.current_approver_profile_code||""):(row.original.last_actor_profile_code||"")}</p></div>},{accessorKey:"created_at",header:"Created",cell:({getValue})=><span className="text-xs text-slate-500">{formatDateTime(getValue())}</span>},{id:"actions",header:"",cell:({row})=><div className="flex justify-end gap-1" onClick={e=>e.stopPropagation()}><Button size="icon" variant="ghost" title="View trail" onClick={()=>setDetail(row.original.history_id)}><Eye size={16}/></Button>{row.original.status!=="PENDING"&&<Button size="icon" variant="ghost" className="text-red-600" title="Remove admin history" onClick={()=>setDeleting(row.original)}><Trash2 size={16}/></Button>}</div>}
],[]);const selectedCount=Object.values(selection).filter(Boolean).length;return <><PageHeader title="Request & Approval History" description="Admin-only audit view across every level, module, approver and outcome." actions={<Badge tone="purple"><UsersRound size={13}/>Admin Audit</Badge>}/><div className="mb-4 flex flex-wrap gap-2"><div className="relative min-w-64 flex-1 max-w-md"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input className="pl-9" placeholder="Request number, person or code…" value={search} onChange={e=>setSearch(e.target.value)}/></div><Select className="w-40" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="REJECTED">Rejected</option></Select><Select className="w-56" value={module} onChange={e=>setModule(e.target.value)}><option value="">All modules</option>{modules.map(m=><option key={m} value={m}>{titleCase(m)}</option>)}</Select>{selectedCount>0&&<Button variant="danger" size="sm" disabled={bulk.isPending} onClick={()=>bulk.mutate()}><Trash2 size={15}/>Delete {selectedCount} completed histories</Button>}</div>{q.isLoading?<LoadingState/>:q.isError?<ErrorState error={q.error}/>:<DataTable columns={columns} data={q.data?.history||[]} selectedRows={selection} setSelectedRows={setSelection} onRowClick={r=>setDetail(r.history_id)}/>}<HistoryDetails id={detail} open={Boolean(detail)} onOpenChange={v=>!v&&setDetail(null)}/><ConfirmDialog open={Boolean(deleting)} onOpenChange={v=>!v&&setDeleting(null)} title="Remove this admin history entry?" description="This removes only the Admin audit-list copy. Operational approval history and business records are kept." confirmLabel="Remove History" destructive onConfirm={()=>remove.mutate(deleting.history_id)}/></>}
