import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { BookOpenCheck, Boxes, GraduationCap } from "lucide-react";
import { customerApi, eProductApi, visitApi } from "@/api/crmApi";
import PageHeader from "@/components/common/PageHeader";
import LoadingState from "@/components/common/LoadingState";
import ErrorState from "@/components/common/ErrorState";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select } from "@/components/ui/select";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/utils/format";

export default function EProductsPage() {
  const [customerId, setCustomerId] = useState(""); const [brandId, setBrandId] = useState(""); const [productId, setProductId] = useState(""); const [sessionId, setSessionId] = useState("");
  const customersQ = useQuery({ queryKey: ["customers", "eproduct-picker"], queryFn: () => customerApi.list({}) });
  const dsrQ = useQuery({ queryKey: ["dsr", "eproduct-meta", customerId], queryFn: () => visitApi.dsrEntry({ customerId: Number(customerId) }), enabled: Boolean(customerId) });
  const productsQ = useQuery({ queryKey: ["eproducts", "brand", brandId], queryFn: () => eProductApi.productsByBrand(brandId), enabled: Boolean(brandId) });
  const detailQ = useQuery({ queryKey: ["eproducts", productId, sessionId, customerId], queryFn: () => eProductApi.details(productId, { academicSessionId: Number(sessionId), customerId: Number(customerId) }), enabled: Boolean(productId && sessionId && customerId) });
  const brands = dsrQ.data?.brands || []; const sessions = dsrQ.data?.academicSessions || dsrQ.data?.academic_sessions || []; const product = detailQ.data?.productDetails?.[0]; const classes = detailQ.data?.classes || [];
  return <><PageHeader title="E-Product Catalogue" description="Browse CRM E-Products by customer, academic session and brand, including previous sales stage context."/>
    <Card className="mb-5"><CardContent className="grid gap-3 p-5 md:grid-cols-4"><div><p className="mb-1.5 text-sm font-semibold">Customer</p><Select value={customerId} onChange={(e) => {setCustomerId(e.target.value);setBrandId("");setProductId("");setSessionId("");}}><option value="">Select customer</option>{(customersQ.data?.customers || []).map((c) => <option key={c.id} value={c.id}>{c.customer_name}</option>)}</Select></div><div><p className="mb-1.5 text-sm font-semibold">Academic Session</p><Select disabled={!customerId} value={sessionId} onChange={(e) => setSessionId(e.target.value)}><option value="">Select session</option>{sessions.map((s) => <option key={s.id} value={s.id}>{s.session_name || s.name}</option>)}</Select></div><div><p className="mb-1.5 text-sm font-semibold">Brand</p><Select disabled={!customerId} value={brandId} onChange={(e) => {setBrandId(e.target.value);setProductId("");}}><option value="">Select brand</option>{brands.map((b) => <option key={b.id} value={b.id}>{b.brand_name || b.name}</option>)}</Select></div><div><p className="mb-1.5 text-sm font-semibold">Product</p><Select disabled={!brandId} value={productId} onChange={(e) => setProductId(e.target.value)}><option value="">Select product</option>{(productsQ.data?.productList || []).map((p) => <option key={p.id} value={p.id}>{p.product_name}</option>)}</Select></div></CardContent></Card>
    {(dsrQ.isLoading || productsQ.isLoading || detailQ.isLoading) && <LoadingState/>}{(dsrQ.isError || productsQ.isError || detailQ.isError) && <ErrorState error={dsrQ.error || productsQ.error || detailQ.error}/>} {product && <div className="grid gap-5 lg:grid-cols-[1fr_.7fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><BookOpenCheck size={19}/>{product.eProductName}</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs uppercase text-slate-400">List Price</p><p className="mt-1 text-xl font-black">{formatCurrency(product.listPrice)}</p></div><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800"><p className="text-xs uppercase text-slate-400">Subject</p><p className="mt-1 text-lg font-bold">{product.subjectName || "—"}</p></div><div className="rounded-xl bg-slate-50 p-4 dark:bg-slate-800 sm:col-span-2"><p className="text-xs uppercase text-slate-400">Previous Sales Stage</p><div className="mt-2 flex items-center gap-2"><Badge tone="purple">{product.previousSalesStage || "No previous stage"}</Badge>{product.previousStageSequenceNum > 0 && <span className="text-xs text-slate-500">Sequence {product.previousStageSequenceNum}</span>}</div></div></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><GraduationCap size={19}/>Applicable Classes</CardTitle></CardHeader><CardContent><div className="flex flex-wrap gap-2">{classes.length ? classes.map((c) => <Badge key={c.classNumId} tone="blue">{c.className}</Badge>) : <p className="text-sm text-slate-500">No class mapping.</p>}</div></CardContent></Card></div>}
    {!product && customerId && <Card><CardContent className="flex items-center justify-center gap-2 p-10 text-sm text-slate-500"><Boxes size={18}/>Select session, brand and product to inspect E-Product details.</CardContent></Card>}
  </>;
}
